@hostname = localhost
@port = 7071
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}

###
# Submit a demo image
# @name submitDemoImage
POST http://{{host}}/api/process_image HTTP/1.2

< ./SampleData/IMG_0013.JPG

###
# Check camera location from file name
# @name nameCheck
GET http://{{host}}/api/location?name=RC05_test.jpg HTTP/1.2

###
# Get a sample of merged data
# @name mergedData
GET http://{{host}}/api/merged_data HTTP/1.2